### ISSUE TITLE
Support GHC call stacks

### ISSUE THREAD

**Issue by hpdeifel** [mrkkrp/hspec-megaparsec#5]
`hspec` usually outputs the source location of failing tests, but this doesn't work for tests that use combinators from `hspec-megaparsec`. Instead it just prints `Test/Hspec/Megaparsec.hs` as location.

To make this work, hspec-megaparsec would just need to add a `HasCallStack` constraint to every combinator, which is quite trivial to do if you're willing to depend on `hspec-expectations >= 0.8` since it exports `HasCallStack`. Otherwise, you could [steal their code](https://github.com/hspec/hspec-expectations/blob/d4a0cf5c86bfc67705098d35f95c4642428555b1/src/Test/Hspec/Expectations.hs#L64)

**Comment by mrkkrp** [comment]
Would it be possible for you to open a PR for this?
